const csvPath='./btc-price all.csv'
const startDateUtc=new Date(Date.UTC(2017,9,1))
const endDateUtc=new Date(Date.UTC(2025,10,15))
let priceRows=[]
let ahrMap=new Map()
let chart
let gPriceMap=new Map()
let maCache={}
function fmtUsd(n){return '$'+n.toLocaleString('en-US',{maximumFractionDigits:2})}
function fmtBtc(n){return n.toFixed(8)}
function toKey(d){return d.toISOString().slice(0,10)}
function parseDateStr(s){const parts=s.includes('-')?s.split('-'):s.split('/');const y=parseInt(parts[0],10);const m=parseInt(parts[1],10)-1;const d=parseInt(parts[2],10);return new Date(Date.UTC(y,m,d))}
async function loadCsv(){const res=await fetch(csvPath+'?v='+Date.now());const txt=await res.text();const lines=txt.trim().split(/\r?\n/);const rows=[];for(let i=1;i<lines.length;i++){const [ds,ps]=lines[i].split(',');const date=parseDateStr(ds.trim());const price=parseFloat(ps.trim());rows.push({date,price})}rows.sort((a,b)=>a.date-b.date);return rows}
function filterRange(rows,s,e){return rows.filter(r=>r.date>=s&&r.date<=e)}
function buildPriceMap(rows){const m=new Map();for(const r of rows){m.set(toKey(r.date),r.price)}return m}
function rollingDcaCost(rows){const invs=rows.map(r=>1/r.price);let sum=0;const costs=new Map();for(let i=0;i<rows.length;i++){sum+=invs[i];if(i>=200){sum-=invs[i-200]}if(i>=199){const cost=200/sum;costs.set(toKey(rows[i].date),cost)} }return costs}
function indexGrowthValuation(ageDays){const v=Math.pow(10,5.84*Math.log10(ageDays)-17.01);return v}
function daysSinceGenesis(d){const genesis=new Date(Date.UTC(2009,0,3));const ms=24*3600*1000;return Math.floor((d-genesis)/ms)+1}
function computeAhr(rows){const dca=rollingDcaCost(rows);const m=new Map();for(const r of rows){const k=toKey(r.date);if(!dca.has(k))continue;const age=daysSinceGenesis(r.date);const iv=indexGrowthValuation(age);const a=(r.price/dca.get(k))*(r.price/iv);m.set(k,a)}return m}
function movingAverageMap(rows,window){const key='ma_'+window;if(maCache[key])return maCache[key];let sum=0;const m=new Map();for(let i=0;i<rows.length;i++){sum+=rows[i].price;if(i>=window){sum-=rows[i-window].price}if(i>=window-1){m.set(toKey(rows[i].date),sum/window)} }maCache[key]=m;return m}
function lastDayOfMonth(y,m){return new Date(Date.UTC(y,m+1,0))}
function getMonthlyDates(s,e,dom,priceMap){const dates=[];let y=s.getUTCFullYear();let m=s.getUTCMonth();while(y<e.getUTCFullYear()||(y===e.getUTCFullYear()&&m<=e.getUTCMonth())){const ld=lastDayOfMonth(y,m);let d=Math.min(dom,ld.getUTCDate());let dt=new Date(Date.UTC(y,m,d));if(dt<s)dt=s;if(dt>ld)dt=ld;const k=toKey(dt);if(priceMap.has(k)&&dt>=s&&dt<=e)dates.push(dt);m++;if(m>11){m=0;y++}}return dates}
function getAhrDates(rowsInRange,threshold){const dates=[];for(const r of rowsInRange){const k=toKey(r.date);const a=ahrMap.get(k);if(a!==undefined&&a<=threshold)dates.push(r.date)}return dates}
function getAhrMonthlyDates(rowsInRange,s,e,threshold,priceMap){const dates=[];let y=s.getUTCFullYear();let m=s.getUTCMonth();while(y<e.getUTCFullYear()||(y===e.getUTCFullYear()&&m<=e.getUTCMonth())){const monthStart=new Date(Date.UTC(y,m,1));const ms=monthStart<s?s:monthStart;const monthEnd=lastDayOfMonth(y,m);const me=monthEnd>e?e:monthEnd;let picked=null;for(const r of rowsInRange){if(r.date>=ms&&r.date<=me){const a=ahrMap.get(toKey(r.date));if(a!==undefined&&a<=threshold){picked=r.date;break}}}if(!picked){const k=toKey(me);if(priceMap.has(k))picked=me}if(picked)dates.push(picked);m++;if(m>11){m=0;y++}}return dates}
function getMaDates(rowsInRange,maMap,op){const dates=[];for(const r of rowsInRange){const k=toKey(r.date);if(!maMap.has(k))continue;const ma=maMap.get(k);if(op==='lte'){if(r.price<=ma)dates.push(r.date)}else{if(r.price>=ma)dates.push(r.date)} }return dates}
function getMaMonthlyDates(rowsInRange,s,e,maMap,op,priceMap){const dates=[];let y=s.getUTCFullYear();let m=s.getUTCMonth();while(y<e.getUTCFullYear()||(y===e.getUTCFullYear()&&m<=e.getUTCMonth())){const monthStart=new Date(Date.UTC(y,m,1));const ms=monthStart<s?s:monthStart;const monthEnd=lastDayOfMonth(y,m);const me=monthEnd>e?e:monthEnd;let picked=null;for(const r of rowsInRange){if(r.date>=ms&&r.date<=me){const k=toKey(r.date);if(maMap.has(k)){const ma=maMap.get(k);if(op==='lte'){if(r.price<=ma){picked=r.date;break}}else{if(r.price>=ma){picked=r.date;break}}}}}if(!picked){const k=toKey(me);if(priceMap.has(k))picked=me}if(picked)dates.push(picked);m++;if(m>11){m=0;y++}}return dates}
function computeSeries(rowsInRange,priceMap,dates,amount){const dateSet=new Set(dates.map(toKey));const labels=[];const invested=[];const value=[];const prices=[];let totalInvested=0;let btc=0;const buyMarkers=[];for(const r of rowsInRange){const k=toKey(r.date);labels.push(k);const p=priceMap.get(k);if(dateSet.has(k)){const addBtc=amount/p;btc+=addBtc;totalInvested+=amount;buyMarkers.push({x:k,y:btc*p})}value.push(btc*p);invested.push(totalInvested);prices.push(p)}return{labels,invested,value,prices,totalInvested,btc,buyCount:dates.length,buyMarkers}}
function renderChart(labels,invested,value,prices,buyMarkers){const ctx=document.getElementById('chart').getContext('2d');if(chart)chart.destroy();const cfg={type:'line',data:{labels:labels,datasets:[{label:'期末资产价值',data:value,borderColor:'#FF9900',backgroundColor:'rgba(255,153,0,0.15)',borderWidth:2,pointRadius:0,tension:0.25,yAxisID:'y'},{label:'累计投入',data:invested,borderColor:'#1A1A1A',backgroundColor:'rgba(26,26,26,0.1)',borderWidth:2,pointRadius:0,tension:0.25,yAxisID:'y'},{label:'BTC价格',data:prices,borderColor:'#3366FF',backgroundColor:'rgba(51,102,255,0.12)',borderWidth:2,pointRadius:0,tension:0.25,yAxisID:'y1'},{type:'scatter',label:'买入标记',data:buyMarkers,borderColor:'#FF9900',backgroundColor:'#FF9900',pointRadius:3,hoverRadius:6,yAxisID:'y'}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{tooltip:{callbacks:{footer:function(items){if(!items||!items.length)return '';const k=items[0].label;const p=gPriceMap.get(k);const a=ahrMap.get(k);const priceStr=p?('$'+Number(p).toLocaleString('en-US')):'-';const aStr=(a!==undefined)?a.toFixed(4):'-';const side=document.getElementById('price-side');if(side)side.textContent=priceStr;return ['价格 '+priceStr,'AHR999 '+aStr]}}}},scales:{y:{grid:{color:'#E0E0E0'},ticks:{callback:function(v){return '$'+Number(v).toLocaleString('en-US')}}},y1:{position:'right',grid:{drawOnChartArea:false},ticks:{callback:function(v){return '$'+Number(v).toLocaleString('en-US')}}}}}};chart=new Chart(ctx,cfg);const keys=buyMarkers.map(m=>m.x);const amountEl=document.getElementById('amount');const amount=Math.max(1,Number(amountEl.value||100));renderTableKeys(keys,amount)}
function updateMetrics(totalInvested,finalValue,btc,buyCount){const profit=finalValue-totalInvested;const roi=totalInvested>0?profit/totalInvested:0;document.getElementById('m-invested').textContent=fmtUsd(totalInvested);document.getElementById('m-value').textContent=fmtUsd(finalValue);document.getElementById('m-profit').textContent=fmtUsd(profit)+'  ('+(roi*100).toFixed(2)+'%)';document.getElementById('m-btc').textContent=fmtBtc(btc);document.getElementById('m-count').textContent=String(buyCount)}
function getMode(){const active=document.querySelector('.tab.active');return active.getAttribute('data-mode')}
function setActiveTab(mode){document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.getAttribute('data-mode')===mode)});document.getElementById('monthly-controls').classList.toggle('hidden',mode!=='monthly');document.getElementById('ahr-controls').classList.toggle('hidden',mode!=='ahr');document.getElementById('ma-controls').classList.toggle('hidden',mode!=='ma')}
async function init(){priceRows=await loadCsv();ahrMap=computeAhr(priceRows);gPriceMap=buildPriceMap(priceRows);const amountInput=document.getElementById('amount');const domRange=document.getElementById('dom');const domValue=document.getElementById('dom-value');const thresholdSel=document.getElementById('ahr-threshold');const tabs=document.querySelectorAll('.tab');tabs.forEach(t=>t.addEventListener('click',()=>{setActiveTab(t.getAttribute('data-mode'))}));domRange.addEventListener('input',()=>{domValue.textContent=domRange.value});const sdInput=document.getElementById('start-date');const edInput=document.getElementById('end-date');if(sdInput)sdInput.value=toKey(startDateUtc);if(edInput)edInput.value=toKey(endDateUtc);document.getElementById('run').addEventListener('click',()=>{const mode=getMode();const amount=Math.max(1,Number(amountInput.value||100));const sdStr=sdInput?sdInput.value:'';const edStr=edInput?edInput.value:'';let s=startDateUtc;let e=endDateUtc;if(sdStr){s=parseDateStr(sdStr)}if(edStr){e=parseDateStr(edStr)}if(s>e){return}const filtered=filterRange(priceRows,s,e);let dates=[];if(mode==='monthly'){dates=getMonthlyDates(s,e,Number(domRange.value),gPriceMap)}else if(mode==='ahr'){const freq=document.getElementById('ahr-frequency').value;if(freq==='monthly'){dates=getAhrMonthlyDates(filtered,s,e,Number(thresholdSel.value),gPriceMap)}else{dates=getAhrDates(filtered,Number(thresholdSel.value))}}else{const winSel=document.getElementById('ma-window');const opSel=document.getElementById('ma-operator');const freq=document.getElementById('ma-frequency').value;const win=Number(winSel.value);const maMap=movingAverageMap(priceRows,win);if(freq==='monthly'){dates=getMaMonthlyDates(filtered,s,e,maMap,opSel.value,gPriceMap)}else{dates=getMaDates(filtered,maMap,opSel.value)}}const series=computeSeries(filtered,gPriceMap,dates,amount);renderChart(series.labels,series.invested,series.value,series.prices,series.buyMarkers);const lastKey=toKey(e);const finalPrice=gPriceMap.get(lastKey);const side=document.getElementById('price-side');if(side)side.textContent=fmtUsd(finalPrice);updateMetrics(series.totalInvested,series.btc*finalPrice,series.btc,series.buyCount);const sub=document.getElementById('subtitle');if(sub)sub.textContent='数据范围 '+toKey(s)+' 至 '+toKey(e)});document.getElementById('run').click()}
function renderTableKeys(keys,amount){const tbody=document.getElementById('buy-tbody');if(!tbody)return;const rows=keys.map(k=>{const p=gPriceMap.get(k);const b=amount>0&&p>0?(amount/p):0;return{key:k,price:p,btc:b}});tbody.innerHTML=rows.map(r=>'<tr><td>'+r.key+'</td><td>'+fmtUsd(r.price)+'</td><td>'+fmtUsd(amount)+'</td><td>'+fmtBtc(r.btc)+'</td></tr>').join('')}
window.addEventListener('DOMContentLoaded',init)